version: '3.1'

# Based on https://github.com/vegasbrianc/prometheus

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    build: ./prometheus
    image: lmhd/twitch_exporter_prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
# Uncomment this if you want to view prometheus directly
#    ports:
#      - 9090:9090
    networks:
      - back-tier
    restart: always

  twitch_exporter:
    build:
      context:    .
      dockerfile: Dockerfile
    image: lmhd/twitch_exporter
# Uncomment this if you want to view the twitch exporter directly
#    ports:
#      - 8080:8080
    networks:
      - back-tier
    environment:
      # Values of these come from .env file
      LOG_LEVEL:
      KRAKEN_CLIENT_ID:
      TWITCH_CHANNELS:
    restart: always

  grafana:
    build: ./grafana
    image: lmhd/twitch_exporter_grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always
