{
 "title": "Desert Bus Dashboard",
 "time": { "from": "2018-11-09T18:00:00.000Z", "to": "2018-11-09T22:05:00.000Z" },
 "templating": {
  "list": [
   { "name": "channel", "label": "Channel", "query": "desertbus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "content": "![Desert Bus 2018 Logo](https://i.imgur.com/8Y9t6EJ.png)"
  },
  {
   "title": "Live Viewers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lmhd_twitch_stream_viewers{channel=~\"$channel\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "content": "# [Donate!](https://desertbus.org/donate)"
  },
  {
   "title": "Followers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lmhd_twitch_channel_followers{channel=~\"$channel\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Time Bussed (approximately)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    { "expr": "time() - 1541786400" }
   ]
  },
  { "title": "Local Bus Time (PST)", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 } },
  {
   "title": "Average Viewers ($channel)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 16 },
   "repeat": "channel",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "lmhd_twitch_stream_viewers{channel=~\"$channel\"}"
    }
   ]
  },
  {
   "title": "Total Views",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lmhd_twitch_channel_views{channel=~\"$channel\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 25 },
   "content": "![Combination of Prometheus logo and Kappa emote from Twitch](https://raw.githubusercontent.com/lucymhdavies/twitch_exporter/master/images/prometheus-kappa.png)"
  }
 ]
}