{
 "title": "Twitch Dashboard (Alt)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "channel",
    "label": "Channel",
    "query": "label_values(lmhd_twitch_stream_viewers,channel)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "content": "![Combination of Prometheus logo and Kappa emote from Twitch](https://raw.githubusercontent.com/lucymhdavies/twitch_exporter/master/images/prometheus-kappa.png)"
  },
  {
   "title": "Live Viewers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lmhd_twitch_stream_viewers{channel=~\"$channel\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lmhd_twitch_channel_followers{channel=~\"$channel\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Average Viewers ($channel)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "repeat": "channel",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "lmhd_twitch_stream_viewers{channel=~\"$channel\"}"
    }
   ]
  },
  {
   "title": "Total Views",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lmhd_twitch_channel_views{channel=~\"$channel\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  }
 ]
}